# Generated by Django 4.2 on 2023-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dontgifapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(blank=True, related_name='categories', to='dontgifapp.gif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
